name: Plosk
version: '${project.version}'
main: me.github.reportcardsmc.plosk.Plosk
softdepend: [ PlotSquared ]
depend: [ Skript ]
authors: [ ReportCardsMC ]
description: Skript addon for plot squared 6 support
