name: Plosk
version: '${project.version}'
main: me.github.reportcardsmc.plosk.Plosk
api-version: 1.16
softdepend: [ PlotSquared ]
depend: [ Skript ]
authors: [ ReportCardsMC ]
description: Skript addon for plot squared 5 support
