name: PlotSk
version: '1.3.2'
main: me.github.reportcardsmc.plotsk.PlotSk
softdepend: [ PlotSquared ]
depend: [ Skript ]
authors: [ ReportCardsMC, Nuutrai ]
description: Skript addon for plot squared 7 support
