name: PlotSk
version: '1.2.0'
main: me.github.reportcardsmc.plotsk.PlotSk
softdepend: [ PlotSquared ]
depend: [ Skript ]
authors: [ ReportCardsMC ]
description: Skript addon for plot squared 7 support
